String localRepo = "file:///home/ubuntu/.m2/repository"

gradle.beforeSettings { settings ->
    settings.pluginManagement.repositories {
        clear()
        maven {
            url=localRepo
        }
        whenObjectAdded { repo ->
            if (repo instanceof MavenArtifactRepository
                    && repo.url.toString() != localRepo) {
                repo.url = localRepo
            }
        }
    }
}

gradle.allprojects { project ->
    project.repositories {
        clear()
        maven { url = localRepo }
        whenObjectAdded { repo ->
            if (repo instanceof MavenArtifactRepository
                    && repo.url.toString() != localRepo) {
                repo.url = localRepo
            }
        }
    }
    buildscript.repositories {
        clear()
        maven {  url=localRepo }

        whenObjectAdded { repo ->
            if (repo instanceof MavenArtifactRepository
                    && repo.url.toString() != localRepo) {
                repo.url = localRepo
            }
        }
    }
}
