<project>
    <groupId>foo</groupId>
    <artifactId>foo</artifactId>
    <version>1</version>
    <modelVersion>4.0.0</modelVersion>
    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.twdata.maven</groupId>
            <artifactId>mojo-executor</artifactId>
            <version>2.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-dependency-plugin</artifactId>
            <version>3.11.0</version>
        </dependency>
    </dependencies>
    <build>
        <directory>${project.basedir}/target</directory>
        <outputDirectory>${project.basedir}/target/classes</outputDirectory>
        <testOutputDirectory>${project.basedir}/target/test-classes</testOutputDirectory>
        <plugins>
            <plugin>
                <groupId>io.github.rockcrafters</groupId>
                <artifactId>rockcraft-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <allowLocal>true</allowLocal>
                        </configuration>
                        <goals>
                            <goal>create-build-rock</goal>
                            <goal>build-build-rock</goal>
                            <goal>push-build-rock</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
