/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.canonical.rockcraft.plugin;

import com.google.gradle.osdetector.OsDetector;
import com.google.gradle.osdetector.OsDetectorPlugin;
import org.gradle.api.Plugin;
import org.gradle.api.Project;

import java.io.IOException;

/**
 * A simple 'hello world' plugin.
 */
public class RockcraftPlugin implements Plugin<Project> {

    public void apply(Project project) {

        project.getPlugins().apply(OsDetectorPlugin.class);

        var options = project.getExtensions().create("rockcraft", RockcraftOptions.class);

        var detector = project.getExtensions().getByType(OsDetector.class);

        if (!"linux".equals(detector.getOs()))
            throw new UnsupportedOperationException("Rockcraft is only supported on linux systems");

        var checkTask = project.getTasks().register("checkRockcraft", s -> {
            s.doFirst( x -> {
                try {
                    var pb = new ProcessBuilder("rockcraft", "--version");
                    pb.inheritIO();
                    var versionProcess = pb.start();
                    int ret = versionProcess.waitFor();
                    if (ret != 0)
                        throw new UnsupportedOperationException("Please install rockcraft 'snap install rockcraft'.");
                }
                catch (IOException | InterruptedException e) {
                    throw new UnsupportedOperationException(e.getMessage());
                }
            });
        });

        var buildTasks = project.getTasksByName("build", false);
        if (buildTasks.isEmpty())
            throw new UnsupportedOperationException("Rockcraft plugin requires build task");

        for (var t : buildTasks)
            t.finalizedBy(checkTask);

        var tasks = project.getTasksByName("jar", false);
        if (tasks.isEmpty())
            throw new UnsupportedOperationException("Rockcraft plugin requires jar task");
        for (var t : tasks)
            t.finalizedBy(project.getTasks().register("createRockcraft", CreateRockcraftTask.class, options));
    }

}
