/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.canonical.rockcraft.plugin;

import com.google.gradle.osdetector.OsDetectorPlugin;
import com.google.gradle.osdetector.OsDetector;

import org.gradle.api.Project;
import org.gradle.api.plugins.JavaBasePlugin;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Path;

import org.gradle.api.Plugin;

/**
 * A simple 'hello world' plugin.
 */
public class RockcraftPlugin implements Plugin<Project> {

    public void apply(Project project) {

        project.getPlugins().apply(JavaBasePlugin.class);
        project.getPlugins().apply(OsDetectorPlugin.class);

        OsDetector detector = project.getExtensions().getByType(OsDetector.class);

        // Register a task
        var createRockcraft =
            project.getTasks().register("createRockcraft", CreateRockcraftTask.class);

        // run task after jar
        project.getTasks().
            getByName("jar").
            finalizedBy(createRockcraft);
    }

}
